"""add org_id to users

Revision ID: b462c1efe1cc
Revises: 
Create Date: 2026-01-20 18:40:53.786392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b462c1efe1cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ledger_action'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_actor_id'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_created_at'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_doc_id'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_document_id'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_event_type'), table_name='ledger_entries')
    op.drop_index(op.f('idx_ledger_org_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_integrity_checks_id'), table_name='integrity_checks')
    op.drop_table('integrity_checks')
    op.drop_table('trade_status_history')
    op.drop_index(op.f('users_email_ci_unique'), table_name='users')
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trade_transactions_id'), table_name='trade_transactions')
    op.drop_table('trade_transactions')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_trade_documents_id'), table_name='trade_documents')
    op.drop_table('trade_documents')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_documents_hash_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_trade_transaction_documents_id'), table_name='trade_transaction_documents')
    op.drop_table('trade_transaction_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_transaction_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('trade_transaction_documents_document_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['trade_transactions.id'], name=op.f('trade_transaction_documents_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_transaction_documents_pkey'))
    )
    op.create_index(op.f('ix_trade_transaction_documents_id'), 'trade_transaction_documents', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('documents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('integrity_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='documents_created_by_fkey'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='documents_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    sa.UniqueConstraint('doc_number', name='documents_doc_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_hash_key'), 'documents', ['hash_key'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organizations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('name', name='organizations_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('trade_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('trade_documents_trade_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('trade_documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_documents_pkey'))
    )
    op.create_index(op.f('ix_trade_documents_id'), 'trade_documents', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('integrity_check_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('alerts_acknowledged_by_id_fkey')),
    sa.ForeignKeyConstraint(['integrity_check_id'], ['integrity_checks.id'], name=op.f('alerts_integrity_check_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('trade_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('trade_transactions_buyer_id_fkey')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('trade_transactions_seller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_transactions_pkey'))
    )
    op.create_index(op.f('ix_trade_transactions_id'), 'trade_transactions', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trades_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('trade_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('corp_org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank_org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['users.id'], name='trades_bank_id_fkey'),
    sa.ForeignKeyConstraint(['bank_org_id'], ['organizations.id'], name='trades_bank_org_id_fkey'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='trades_buyer_id_fkey'),
    sa.ForeignKeyConstraint(['corp_org_id'], ['organizations.id'], name='trades_corp_org_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='trades_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trades_pkey'),
    sa.UniqueConstraint('trade_num', name='trades_trade_num_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['admin'::character varying, 'bank'::character varying, 'corp'::character varying, 'auditor'::character varying]::text[])", name='users_role_check'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='users_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('users_email_ci_unique'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.create_table('trade_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('trade_status_history_changed_by_fkey')),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('trade_status_history_trade_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_status_history_pkey'))
    )
    op.create_table('integrity_checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stored_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('computed_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('check_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checked_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], name=op.f('integrity_checks_checked_by_fkey')),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name=op.f('integrity_checks_doc_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('integrity_checks_pkey'))
    )
    op.create_index(op.f('ix_integrity_checks_id'), 'integrity_checks', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hash_before', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('hash_after', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name=op.f('ledger_entries_doc_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('ledger_entries_org_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ledger_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ledger_entries_pkey'))
    )
    op.create_index(op.f('idx_ledger_org_id'), 'ledger_entries', ['org_id'], unique=False)
    op.create_index(op.f('idx_ledger_event_type'), 'ledger_entries', ['event_type'], unique=False)
    op.create_index(op.f('idx_ledger_document_id'), 'ledger_entries', ['document_id'], unique=False)
    op.create_index(op.f('idx_ledger_doc_id'), 'ledger_entries', ['doc_id'], unique=False)
    op.create_index(op.f('idx_ledger_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('idx_ledger_actor_id'), 'ledger_entries', ['actor_id'], unique=False)
    op.create_index(op.f('idx_ledger_action'), 'ledger_entries', ['action'], unique=False)
    # ### end Alembic commands ###
